Use yarn magic to generate unit test coverage

diff --git a/.github/workflows/alfa-coverage.yml b/.github/workflows/alfa-coverage.yml
--- a/.github/workflows/alfa-coverage.yml
+++ b/.github/workflows/alfa-coverage.yml
@@ -23,12 +23,22 @@ jobs:
       - name: Build project
         run: yarn build
 
-      - name: Generate coverage reports
-        # The scripts/coverage.sh script needs to be repo specific since
-        # it uses the packages paths. Would be better to work some magic
-        # around `yarn workspaces foreach` but it's a bit tricky without
-        # having a `package.json` script in each package.
-        run: ${{ github.workspace }}/scripts/coverage.sh
+      - name: Generate global coverage report
+        run: yarn coverage
+
+      - name: Generate individual coverage reports
+        # This step does fail due to some packages missing tests.
+        # This still generates the individual reports, and we want to go on.
+        run: >
+          yarn workspaces foreach
+          --all --parallel --no-private
+          --exclude @siteimprove/alfa-test 
+          --exclude @siteimprove/alfa-test-deprecated
+          run yarn coverage:package
+          || true
+
+      - name: Consolidate coverage reports
+        run: yarn generate-unit-test-report
 
       - name: Commit and push changes
         run: |
